# frozen_string_literal: true

require "rails/generators"

module B4um
  module Generators
    class HelpGenerator < Rails::Generators::Base
      desc "Shows an overview of the available b4um generators and features"

      def show_help
        say <<~TEXT

          b4um Generators
          ===============

          INSTALLATION

            bin/rails generate b4um:install

          Installs the b4um base setup:

            - b4um component stylesheets
            - Navigation
            - Navigation Stimulus controller
            - Image preview Stimulus controller
            - Image lightbox Stimulus controller
            - Helper methods
            - Layout integration
            - Bento / card components

          During installation, optional features can be selected:

            - bcrypt for password support
            - Active Storage for image attachments
            - Home page with root route
            - Hero section
            - Footer
            - Footer sitemap
            - Cookie consent

          The sitemap can only be installed when the footer is installed.

          If an optional Gem is selected and is not already installed,
          b4um adds it to the Gemfile and runs bundle install.

          If Active Storage is selected and is not already installed,
          b4um installs Active Storage and runs the database migration.


          HOME PAGE

          The installer can optionally create a home page.

          During installation, b4um asks:

            Create a home page? (y/n)

          When selected, the controller and action can be configured:

            Home controller [Pages]:
            Home action [home]:

          Press Enter to use the defaults.

          With the default configuration, b4um creates:

            app/controllers/pages_controller.rb
            app/views/pages/home.html.erb

          and adds:

            root "pages#home"

          A Home link using root_path is also added to the
          b4um navigation.

          If the application already has a root route, b4um keeps
          the existing root route and does not add a new Home
          navigation link.


          HERO

          The installer can add an optional hero section.

          Select the hero when running:

            bin/rails generate b4um:install

          The hero partial is created at:

            app/views/shared/_hero.html.erb

          The generated hero works without an image by default.

          The template contains examples for:

            - Hero title and text
            - Optional action link
            - Optional hero image

          Hero CSS classes use the b4um-hero prefix.


          BENTO / CARDS

          b4um includes a responsive Bento-style card system.

          Basic example:

            <div class="b4um-grid">
              <article class="b4um-card">
                ...
              </article>
            </div>

          Available card variants:

            b4um-card
            b4um-card--wide
            b4um-card--large
            b4um-card--full
            b4um-card--soft

          Card content classes include:

            b4um-card__eyebrow
            b4um-card__title
            b4um-card__text
            b4um-card__actions
            b4um-card__media
            b4um-card__image

          The Bento grid is responsive and automatically adapts
          to tablet and mobile layouts.

          b4um scaffolds automatically use the Bento card system
          for generated index pages.

          Cards use a repeating layout pattern:

            1 - wide
            2 - soft
            3 - normal
            4 - large
            5 - normal

          Long text fields are shortened on index cards while the
          complete content remains visible on the show page.


          FOOTER

          The installer can add an optional footer.

          Select the footer when running:

            bin/rails generate b4um:install

          The footer partial is created at:

            app/views/shared/_footer.html.erb

          The generated footer includes:

            - Automatic current year
            - Application name placeholder
            - Automatic legal page links generated by b4um:controller
            - Optional sitemap partial
            - Optional cookie settings control

          Footer CSS classes use the b4um-footer prefix.

          The sitemap is not hard-coded into the footer. When the
          sitemap is selected during installation, b4um creates a
          separate sitemap partial and renders it inside the footer.


          SITEMAP

          The installer can optionally add a sitemap to the footer.

          The footer must be installed before the sitemap can be selected.

          During installation, b4um asks:

            Add a sitemap to the footer? (y/n)

          When the sitemap is enabled, the number of sitemap columns
          can be selected:

            Number of sitemap columns [4]:

          The sitemap supports between 2 and 5 columns.

          Press Enter to use the default of 4 columns.

          After selecting the number of columns, b4um asks for the
          title of each selected column.

          With the default four-column setup:

            Sitemap column 1 title [Kontakt]:
            Sitemap column 2 title [Inhalte]:
            Sitemap column 3 title [Service]:
            Sitemap column 4 title [Mehr]:

          When five columns are selected, an additional title is
          requested:

            Sitemap column 5 title [Weitere]:

          Press Enter to keep the default title shown in brackets.

          Only the selected number of sitemap columns is written to
          the configuration.

          The sitemap partial is created at:

            app/views/shared/_sitemap.html.erb

          The sitemap Stimulus controller is created at:

            app/javascript/controllers/sitemap_controller.js

          The sitemap partial is rendered inside:

            app/views/shared/_footer.html.erb

          The sitemap configuration is stored in:

            config/b4um.yml

          Example using the default four columns:

            sitemap:
              - key: column_1
                title: Kontakt
              - key: column_2
                title: Inhalte
              - key: column_3
                title: Service
              - key: column_4
                title: Mehr

            legal_links:
              placement: footer

          A two-column sitemap contains only column_1 and column_2.

          A five-column sitemap additionally contains:

            column_5

          The sitemap column titles can also be changed later by
          editing config/b4um.yml.

          Available column keys range from:

            column_1

          through:

            column_5

          Only keys for columns that exist in the current sitemap
          configuration should be used.

          The keys identify the sitemap columns independently of their
          visible titles.

          On larger screens, the available sitemap columns are
          distributed automatically across the footer.

          On smaller screens, the sitemap uses its responsive
          collapsible layout.

          Controller actions can be added directly to a sitemap column
          with --sitemap:

            bin/rails generate b4um:controller Pages faq support --sitemap=column_3

          When --sitemap is used, the generated actions are added to the
          selected sitemap column instead of the main navigation.

          Generated sitemap links use Rails route helpers.

          Example:

            links:
              - title: FAQ
                route: faq_path

          Only valid Rails path helpers ending in _path are resolved
          by the b4um sitemap helper.

          Legal pages can remain in the separate legal footer area:

            legal_links:
              placement: footer

          This is the default configuration.

          Legal pages can alternatively be placed in any existing
          sitemap column:

            legal_links:
              placement: column_4

          When legal pages are assigned to a sitemap column, b4um adds
          them to that column automatically and does not duplicate them
          in the separate legal footer area.

          The placement uses the sitemap column key, not its visible
          title. This allows sitemap column titles to be changed freely.


          COOKIE CONSENT

          The installer can optionally add cookie consent.

          During installation, b4um asks:

            Add cookie consent? (y/n)

          Cookie consent can be installed independently of the footer.

          The cookie consent partial is created at:

            app/views/shared/_cookie_consent.html.erb

          The cookie consent Stimulus controller is created at:

            app/javascript/controllers/cookie_consent_controller.js

          The visitor's consent choice is stored in the browser's
          local storage.

          If both the footer and cookie consent are installed, b4um
          automatically adds a Cookie-Einstellungen control to the
          footer.

          This control allows visitors to reopen the cookie consent
          banner and change their choice later.

          Cookie consent can also be installed without a footer. In
          that case, the cookie consent banner still works, but no
          cookie settings control is added to the footer.


          SCAFFOLD

            bin/rails generate b4um:scaffold MODEL ATTRIBUTES

          Example:

            bin/rails generate b4um:scaffold User name:string email:string

          b4um scaffold features:

            - b4um forms
            - b4um index, show, new and edit views
            - Bento index layout by default
            - Optional table index layout
            - Select fields with custom labels
            - Radio fields with custom labels
            - Automatic navigation entry
            - Active navigation state
            - Form validation errors
            - Flash messages
            - Password field support
            - Optional readable URL parameters

          Select fields can be generated with:

            --select='FIELD:VALUE=LABEL,VALUE=LABEL'

          Example:

            bin/rails generate b4um:scaffold Product name:string status:string --select='status:Active=Aktiv,Inactive=Inaktiv'

          Radio fields use the same value and label syntax:

            --radio='FIELD:VALUE=LABEL,VALUE=LABEL'

          Example:

            bin/rails generate b4um:scaffold Product name:string condition:string --radio='condition:new=Neu,used=Gebraucht,refurbished=Generalüberholt'

          The configured values are stored in the database. The labels
          are displayed in forms, resource views and table layouts.

          Select and radio options can be used together for different
          fields.

          Example:

            bin/rails generate b4um:scaffold Product name:string status:string condition:string --select='status:Active=Aktiv,Inactive=Inaktiv' --radio='condition:new=Neu,used=Gebraucht'

          The same field cannot use both --select and --radio.

          The default index uses the b4um Bento card layout.

          To generate a table index instead, use:

            --layout=table

          Example:

            bin/rails generate b4um:scaffold Product name:string description:text price:decimal status:string --layout=table

          Table layouts automatically:

            - Use the responsive b4um table component
            - Shorten text fields to 100 characters
            - Display a status field as a b4um badge
            - Include an actions column
            - Include the b4um empty state


          READABLE URL PARAMETERS

          b4um can generate readable URLs while keeping
          the database ID in the URL.

          When creating a new scaffold, use:

            --param=ATTRIBUTE

          Example:

            bin/rails generate b4um:scaffold Article title:string body:text --param=title

          For an existing model, readable URLs can also be
          added later with:

            bin/rails generate b4um:readable MODEL ATTRIBUTE

          Example:

            bin/rails generate b4um:readable Product name

          Both variants add a to_param method to the model.

          Example:

            def to_param
              "\#{id} \#{name}".parameterize
            end

          Example URL:

            /products/17-macbook-air

          The ID remains part of the URL, so the standard Rails
          resource lookup can still be used.

          The readable part of the URL is updated automatically
          when the selected attribute changes.

          The b4um:readable generator requires:

            - An existing model
            - An existing model attribute
            - No existing custom to_param method

          Existing to_param methods are not overwritten.


          PASSWORDS

          For password authentication, use:

            password_digest:string

          Example:

            bin/rails generate b4um:scaffold User name:string email:string password_digest:string

          The b4um scaffold automatically creates password fields
          instead of displaying password_digest directly.

          Password support requires bcrypt.

          Select bcrypt when running:

            bin/rails generate b4um:install

          b4um adds bcrypt to the Gemfile if necessary and installs
          the selected Gem automatically.


          AUTHENTICATION

            bin/rails generate b4um:authentication MODEL

          Adds session-based authentication for an existing model.

          Example:

            bin/rails generate b4um:authentication User

          The authentication model can have any name, for example:

            User
            Admin
            Member

          The selected model must:

            - Already exist
            - Use has_secure_password
            - Have a password_digest column
            - Use bcrypt

          Authentication uses an email attribute for login.

          Example:

            bin/rails generate b4um:scaffold User name:string email:string password_digest:string
            bin/rails generate b4um:authentication User

          The authentication generator adds:

            - Sessions controller
            - Login form
            - Login and logout routes
            - Session-based current account helper
            - logged_in? helper
            - require_login helper
            - Login and logout navigation controls

          The generated helper name follows the selected model.

          For User:

            current_user

          For Admin:

            current_admin

          Existing controllers can optionally be protected with --protect.

          Example:

            bin/rails generate b4um:authentication User --protect=Products

          Multiple controllers can be protected in one run:

            bin/rails generate b4um:authentication User --protect=Products,Articles,Comments

          Protected controllers receive:

            before_action :require_login, except: [:index, :show]

          This keeps index and show publicly accessible while requiring
          authentication for actions such as new, create, edit, update
          and destroy.

          For protected b4um resources, authentication also updates
          the generated interface for logged-out visitors.

          On index pages:

            - New is hidden

          On show pages:

            - Edit is hidden
            - Destroy is hidden
            - Back remains visible

          These controls remain available to logged-in users.
          The controller protection remains the security boundary;
          hiding the controls only keeps the public interface consistent.

          Additional controllers can be protected later by running the
          authentication generator again.

          Example:

            bin/rails generate b4um:authentication User --protect=Comments

          Existing authentication helpers, routes and navigation controls
          are not duplicated on repeated runs.

          All controllers passed to --protect must already exist.
          If a protected controller cannot be found, the generator stops
          before changing the application.

          The generator validates its requirements before changing
          the application and reports missing authentication setup
          with a suggested b4um scaffold command.

          Repeated generator runs do not duplicate the authentication
          helpers, routes or navigation controls.


          ACTIVE STORAGE / IMAGES

          Image attachments require Active Storage.

          Select Active Storage when running:

            bin/rails generate b4um:install

          b4um installs Active Storage and runs the required database
          migration automatically if Active Storage is not already installed.


          Single image:

            image:attachment

          Example:

            bin/rails generate b4um:scaffold Article title:string image:attachment

          Multiple images:

            images:attachments

          Example:

            bin/rails generate b4um:scaffold Gallery title:string images:attachments

          Attachments can also be added later to an existing
          b4um resource.

          Single attachment:

            bin/rails generate b4um:attachment MODEL ATTACHMENT

          Example:

            bin/rails generate b4um:attachment Admin avatar

          This adds:

            has_one_attached :avatar

          Multiple attachments:

            bin/rails generate b4um:attachment MODEL ATTACHMENT --multiple

          Example:

            bin/rails generate b4um:attachment Product images --multiple

          This adds:

            has_many_attached :images

          When the corresponding b4um files exist, the attachment
          generator also updates:

            - The existing model
            - The existing b4um form
            - The controller parameters
            - The existing b4um resource partial

          Multiple attachments additionally support:

            - Adding new images without replacing existing images
            - Removing individual existing images
            - Multiple image preview
            - Image gallery with lightbox navigation

          Repeated generator runs do not duplicate existing
          attachment setup.


          Image features:

            - Active Storage integration
            - Image preview before saving
            - Existing image preview while editing
            - Add new images without removing existing images
            - Remove individual existing images
            - Image lightbox
            - Previous / next navigation
            - Mouse and touch swipe
            - Keyboard navigation


          BENTO

            bin/rails generate b4um:bento MODEL

          Generates a reusable b4um Bento partial for an existing model.

          Example:

            bin/rails generate b4um:bento Product

          The default layout is Grid.

          Available layouts:

            bin/rails generate b4um:bento Product
            bin/rails generate b4um:bento Product --layout=grid
            bin/rails generate b4um:bento Product --layout=list
            bin/rails generate b4um:bento Product --layout=alternating
            bin/rails generate b4um:bento Product --layout=bento

          Layouts:

            grid
              The default three-column card grid.
              Adapts to two columns on tablets and one column on mobile.

            list
              A compact horizontal list layout.
              Actions move below the content on mobile.

            alternating
              A spacious alternating layout with the action area
              switching between the left and right side.
              Uses a single-column layout on mobile.

            bento
              The classic Bento layout with mixed card sizes.

          Use --layout=bento to explicitly generate the classic
          Bento design.

          The model and its resource partial must already exist.

          Example resource partial:

            app/views/products/_product.html.erb

          b4um scaffold resource partials support compact mode.
          In Bento cards, text fields are shortened to 160 characters.

          The generated partial is created at:

            app/views/products/_bento.html.erb

          Bento features:

            - Responsive b4um Bento grid
            - Repeating card layout with different card sizes
            - Uses the existing resource partial for card content
            - Actions area with a Show button
            - No migrations, routes or controllers are generated

          Render the partial from an index view with:

            <%= render "bento", products: @products %>

          The partial uses a local collection, so it can also be
          reused with another collection:

            <%= render "products/bento", products: @featured_products %>


          TABLE

            bin/rails generate b4um:table MODEL [FIELDS]

          Generates a reusable b4um table partial for an existing model.

          The model must already exist.

          Fields are optional. If no fields are supplied, the generator
          automatically detects:

            - Database fields
            - Action Text rich text fields
            - Active Storage single attachments
            - Active Storage multiple attachments

          id, created_at and updated_at are excluded automatically.

          Recommended:

            bin/rails generate b4um:table Product

          Fields can also be specified explicitly:

            bin/rails generate b4um:table Product name price status

          Select fields can be configured with --select:

            bin/rails generate b4um:table Product --select='status:active=Active,inactive=Inactive'

          Radio fields can be configured with --radio:

            bin/rails generate b4um:table Product --radio='condition:new=New,used=Used'

          The configured database values are displayed using their labels.

          The generated partial is created at:

            app/views/products/_table.html.erb

          Table features:

            - Automatic field detection from the existing model
            - Responsive b4um table component
            - Model-aware field types
            - Text fields shortened to 100 characters
            - Decimal values formatted with two decimal places
            - Status fields displayed as b4um badges
            - Select and radio labels
            - Action Text / Trix content
            - Lightbox for images embedded in rich text
            - Trix image captions in the lightbox
            - Active Storage single images
            - Active Storage multiple image galleries
            - Image thumbnails and lightbox navigation
            - Mouse and touch drag / swipe
            - Actions column with a Show button
            - Empty-state handling
            - No migrations, routes or controllers are generated

          Running the Table generator automatically switches an existing
          b4um index view to the table partial:

            <%= render "table", products: @products %>

          Running b4um:bento later switches the index back to the Bento
          partial. This also applies to the grid, list and alternating
          Bento layouts.

          The table partial uses a local collection, so it can also be
          reused with another collection:

            <%= render "products/table", products: @featured_products %>


          CONTROLLER

            bin/rails generate b4um:controller NAME ACTIONS

          Example:

            bin/rails generate b4um:controller Pages home about impressum agb

          b4um controller features:

            - Uses the standard Rails controller generator
            - Creates the requested actions and views
            - Adds regular action links to the b4um navigation automatically
            - Adds legal pages to the b4um footer automatically
            - German legal pages: impressum, datenschutz, agb
            - English legal pages: imprint, privacy, privacy_policy,
              terms, terms_and_conditions
            - Legal pages are not added to the main navigation
            - Footer links require the b4um footer to be installed

          Controller actions can also be assigned directly to a sitemap
          column with --sitemap.

          Example:

            bin/rails generate b4um:controller Pages faq support --sitemap=column_3


          PAGINATION

            bin/rails generate b4um:pagination MODEL

          Adds server-side b4um pagination to an existing resource.

          Example:

            bin/rails generate b4um:pagination Product

          By default, 20 records are displayed per page.

          Use a custom page size with:

            bin/rails generate b4um:pagination Product --per-page=50

          The model, controller and index view must already exist.

          Pagination features:

            - Server-side pagination using Active Record limit and offset
            - No additional pagination gem required
            - Previous and Next navigation
            - Numbered page navigation
            - Preserves existing query parameters
            - Works with b4um Bento and Table layouts
            - Invalid or excessive page numbers are handled safely
            - Shared pagination core can be reused by other b4um features


          INFINITE SCROLL

            bin/rails generate b4um:infinite_scroll MODEL

          Adds automatic infinite scrolling to an existing resource.

          Example:

            bin/rails generate b4um:infinite_scroll Product

          By default, 20 records are loaded per page.

          Use a custom page size with:

            bin/rails generate b4um:infinite_scroll Product --per-page=50

          The model, controller and index view must already exist.

          Infinite Scroll features:

            - Loads additional records automatically while scrolling
            - Server-side pagination using Active Record limit and offset
            - No additional pagination gem required
            - Works with b4um Bento and Table layouts
            - Preserves existing query parameters
            - Stops automatically after the final page
            - Replaces existing b4um pagination navigation
            - Safe repeated generator runs


          SEARCH

            bin/rails generate b4um:search MODEL

          Adds database-backed search to an existing resource.

          Example:

            bin/rails generate b4um:search Product

          The model, controller and index view must already exist.

          Search features:

            - Searches all string and text columns
            - Case-insensitive partial matching
            - Safely escapes search terms
            - Blank searches return the complete collection
            - Works with b4um Bento and Table layouts
            - Works with b4um Pagination and Infinite Scroll
            - Preserves the search query while navigating pages
            - No additional search gem required
            - Safe repeated generator runs


          COMMENTS

            bin/rails generate b4um:comments MODEL

          Example:

            bin/rails generate b4um:comments Article

          Adds polymorphic comments to an existing model.

          b4um comments features:

            - Polymorphic Comment model
            - Comment association on the selected model
            - Nested create and destroy routes
            - Comments controller
            - Comment list and form
            - Delete confirmation
            - b4um form and card styling
            - Support for multiple commentable models
            - Safe repeated generator runs

          Additional models can use the same comments system:

            bin/rails generate b4um:comments Product

          Existing b4um comments controllers are extended automatically.
          Unknown custom comments controllers are left unchanged and cause
          the generator to stop with an error.


          IN-PLACE EDITING

            bin/rails generate b4um:in_place MODEL FIELD [FIELD ...]

          Adds in-place editing to fields of an existing b4um resource.

          Examples:

            bin/rails generate b4um:in_place Product name
            bin/rails generate b4um:in_place Product name price status

          The model, controller and resource routes must already exist.

          The generator detects the field type automatically and creates
          the appropriate in-place editor.

          Supported fields include:

            - String and text fields
            - Numeric and decimal fields
            - Boolean fields
            - Action Text rich text fields
            - Active Storage single image attachments
            - Active Storage multiple image attachments

          Select fields can be configured with --select:

            bin/rails generate b4um:in_place Product status --select='status:Active=Aktiv,Inactive=Inaktiv'

          Radio buttons can be configured with --radio:

            bin/rails generate b4um:in_place Product condition --radio='condition:new=Neu,used=Gebraucht,refurbished=Generalüberholt'

          The value before "=" is stored in the database.
          The optional value after "=" is used as the displayed label.

          In-place editing features:

            - Turbo Frame based editing without an additional in-place gem
            - Click a displayed field to edit it in place
            - Text and rich text fields save when clicking outside
            - Select, radio, and boolean fields save immediately
            - Single and multiple image attachment editing
            - Existing attachments can be removed
            - Validation errors remain visible inside the editor
            - Successful updates can refresh the flash message immediately
            - Existing resource layout remains in place while editing
            - Multiple fields can be added in one generator run
            - Additional fields can be added in later generator runs
            - Safe repeated generator runs

          In-place editing also integrates with b4um authentication.

          Without authentication, generated in-place fields are editable.
          When b4um authentication is installed, editing is restricted to
          logged-in users and the affected controller actions are protected.

          Authentication can be installed before or after in-place editing.
          The generators update the integration automatically in either order.


          TRIX / RICH TEXT

            bin/rails generate b4um:trix MODEL ATTRIBUTE

          Adds Action Text with Trix to an existing b4um resource.

          Example:

            bin/rails generate b4um:trix Article content

          The model and b4um form must already exist. The selected
          attribute does not need to be present in the form yet.

          The generator adds:

            has_rich_text :content

          and adds or replaces the selected form field with a rich
          text editor:

            form.rich_text_area :content

          The corresponding b4um resource field is also added when
          it does not already exist.

          Trix / Rich Text features:

            - Installs Action Text automatically when necessary
            - Adds the rich text association to the model
            - Adds or replaces the selected form field
            - Adds the rich text field to the b4um resource when necessary
            - Preserves compact Bento text using plain text
            - Image lightbox for images inside rich text
            - Previous / next image navigation
            - Mouse and touch swipe
            - Keyboard navigation
            - Responsive image galleries
            - Sticky Trix toolbar
            - Headings H1 through H6
            - Left, center, and right text alignment
            - Text and background colors
            - Horizontal rules
            - Editable DIV, SECTION, and ARTICLE containers with IDs
            - Container formatting remains fully editable
            - Active container buttons can remove the wrapper again
            - Safe repeated generator runs


          HELP

            bin/rails generate b4um:help

          Shows this overview.

        TEXT
      end
    end
  end
end
