# frozen_string_literal: true

require "spec_helper"
require "generators/b4um/help/help_generator"

RSpec.describe B4um::Generators::HelpGenerator do
  it "loads the b4um help generator" do
    expect(described_class).to be < Rails::Generators::Base
  end

  it "documents the b4um install generator" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "bin/rails generate b4um:install"
      )

      expect(text).to include(
        "bcrypt for password support"
      )

      expect(text).to include(
        "Active Storage for image attachments"
      )

      expect(text).to include(
        "Home page with root route"
      )

      expect(text).to include(
        "HOME PAGE"
      )

      expect(text).to include(
        "Create a home page? (y/n)"
      )

      expect(text).to include(
        "Home controller [Pages]:"
      )

      expect(text).to include(
        "Home action [home]:"
      )

      expect(text).to include(
        'root "pages#home"'
      )

      expect(text).to include(
        "root_path"
      )

      expect(text).to include(
        "If the application already has a root route"
      )

      expect(text).to include(
        "Hero section"
      )

      expect(text).to include(
        "Footer"
      )

      expect(text).to include(
        "Footer sitemap"
      )

      expect(text).to include(
        "Cookie consent"
      )

      expect(text).to include(
        "The sitemap can only be installed when the footer is installed."
      )

      expect(text).to include(
        "Automatic legal page links generated by b4um:controller"
      )
    end

    generator.show_help
  end

  it "documents the b4um Bento card system" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "BENTO / CARDS"
      )

      expect(text).to include(
        "b4um-card--wide"
      )

      expect(text).to include(
        "b4um-card--large"
      )

      expect(text).to include(
        "b4um-card--full"
      )

      expect(text).to include(
        "b4um-card--soft"
      )

      expect(text).to include(
        "b4um scaffolds automatically use the Bento card system"
      )

      expect(text).to include(
        "1 - wide"
      )

      expect(text).to include(
        "4 - large"
      )

      expect(text).to include(
        "Long text fields are shortened on index cards"
      )
    end

    generator.show_help
  end

  it "documents the b4um footer" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "FOOTER"
      )

      expect(text).to include(
        "app/views/shared/_footer.html.erb"
      )

      expect(text).to include(
        "Automatic current year"
      )

      expect(text).to include(
        "Automatic legal page links generated by b4um:controller"
      )

      expect(text).to include(
        "Optional sitemap partial"
      )

      expect(text).to include(
        "Optional cookie settings control"
      )

      expect(text).to include(
        "The sitemap is not hard-coded into the footer."
      )
    end

    generator.show_help
  end

  it "documents the b4um sitemap installation and configuration" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "SITEMAP"
      )

      expect(text).to include(
        "Add a sitemap to the footer? (y/n)"
      )

      expect(text).to include(
        "Number of sitemap columns [4]:"
      )

      expect(text).to include(
        "supports between 2 and 5 columns"
      )

      expect(text).to include(
        "default of 4 columns"
      )

      expect(text).to include(
        "Sitemap column 1 title [Kontakt]:"
      )

      expect(text).to include(
        "Sitemap column 2 title [Inhalte]:"
      )

      expect(text).to include(
        "Sitemap column 3 title [Service]:"
      )

      expect(text).to include(
        "Sitemap column 4 title [Mehr]:"
      )

      expect(text).to include(
        "Sitemap column 5 title [Weitere]:"
      )

      expect(text).to include(
        "Press Enter to keep the default title shown in brackets."
      )

      expect(text).to include(
        "Only the selected number of sitemap columns is written"
      )

      expect(text).to include(
        "app/views/shared/_sitemap.html.erb"
      )

      expect(text).to include(
        "app/javascript/controllers/sitemap_controller.js"
      )

      expect(text).to include(
        "app/views/shared/_footer.html.erb"
      )

      expect(text).to include(
        "config/b4um.yml"
      )

      expect(text).to include(
        "column_1"
      )

      expect(text).to include(
        "column_5"
      )

      expect(text).to include(
        "Only keys for columns that exist in the current sitemap"
      )

      expect(text).to include(
        "distributed automatically across the footer"
      )

      expect(text).to include(
        "responsive"
      )

      expect(text).to include(
        "--sitemap=column_3"
      )

      expect(text).to include(
        "route: faq_path"
      )

      expect(text).to include(
        "Only valid Rails path helpers ending in _path"
      )

      expect(text).to include(
        "placement: footer"
      )

      expect(text).to include(
        "placement: column_4"
      )

      expect(text).to include(
        "does not duplicate them"
      )

      expect(text).to include(
        "sitemap column key"
      )
    end

    generator.show_help
  end

  it "documents b4um cookie consent" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "COOKIE CONSENT"
      )

      expect(text).to include(
        "Add cookie consent? (y/n)"
      )

      expect(text).to include(
        "Cookie consent can be installed independently of the footer."
      )

      expect(text).to include(
        "app/views/shared/_cookie_consent.html.erb"
      )

      expect(text).to include(
        "app/javascript/controllers/cookie_consent_controller.js"
      )

      expect(text).to include(
        "local storage"
      )

      expect(text).to include(
        "Cookie-Einstellungen"
      )

      expect(text).to include(
        "reopen the cookie consent"
      )

      expect(text).to include(
        "Cookie consent can also be installed without a footer."
      )
    end

    generator.show_help
  end

  it "documents readable URL parameters" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "READABLE URL PARAMETERS"
      )

      expect(text).to include(
        "--param=ATTRIBUTE"
      )

      expect(text).to include(
        "--param=title"
      )

      expect(text).to include(
        "bin/rails generate b4um:readable MODEL ATTRIBUTE"
      )

      expect(text).to include(
        "bin/rails generate b4um:readable Product name"
      )

      expect(text).to include(
        "\"\#{id} \#{name}\".parameterize"
      )

      expect(text).to include(
        "/products/17-macbook-air"
      )

      expect(text).to include(
        "Existing to_param methods are not overwritten."
      )
    end

    generator.show_help
  end

  it "documents password support" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "password_digest:string"
      )

      expect(text).to include(
        "Password support requires bcrypt."
      )
    end

    generator.show_help
  end

  it "documents Active Storage image support" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "image:attachment"
      )

      expect(text).to include(
        "images:attachments"
      )

      expect(text).to include(
        "Image preview before saving"
      )

      expect(text).to include(
        "Remove individual existing images"
      )

      expect(text).to include(
        "Image lightbox"
      )

      expect(text).to include(
        "Mouse and touch swipe"
      )

      expect(text).to include(
        "Keyboard navigation"
      )
    end

    generator.show_help
  end

  it "documents the b4um Bento generator" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "BENTO"
      )

      expect(text).to include(
        "bin/rails generate b4um:bento MODEL"
      )

      expect(text).to include(
        "bin/rails generate b4um:bento Product"
      )

      expect(text).to include(
        "app/views/products/_bento.html.erb"
      )

      expect(text).to include(
        "The model and its resource partial must already exist."
      )

      expect(text).to include(
        "app/views/products/_product.html.erb"
      )

      expect(text).to include(
        "text fields are shortened to 160 characters"
      )

      expect(text).to include(
        '<%= render "bento", products: @products %>'
      )

      expect(text).to include(
        '<%= render "products/bento", products: @featured_products %>'
      )

      expect(text).to include(
        "No migrations, routes or controllers are generated"
      )
    end

    generator.show_help
  end

  it "documents the b4um controller generator" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "bin/rails generate b4um:controller NAME ACTIONS"
      )

      expect(text).to include(
        "bin/rails generate b4um:controller Pages home about impressum agb"
      )

      expect(text).to include(
        "Adds regular action links to the b4um navigation automatically"
      )

      expect(text).to include(
        "Adds legal pages to the b4um footer automatically"
      )

      expect(text).to include(
        "German legal pages: impressum, datenschutz, agb"
      )

      expect(text).to include(
        "English legal pages: imprint, privacy, privacy_policy,"
      )

      expect(text).to include(
        "terms, terms_and_conditions"
      )

      expect(text).to include(
        "Legal pages are not added to the main navigation"
      )

      expect(text).to include(
        "Footer links require the b4um footer to be installed"
      )

      expect(text).to include(
        "Controller actions can also be assigned directly to a sitemap"
      )

      expect(text).to include(
        "--sitemap=column_3"
      )
    end

    generator.show_help
  end

  it "documents the b4um pagination generator" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "PAGINATION"
      )

      expect(text).to include(
        "bin/rails generate b4um:pagination MODEL"
      )

      expect(text).to include(
        "bin/rails generate b4um:pagination Product"
      )

      expect(text).to include(
        "bin/rails generate b4um:pagination Product --per-page=50"
      )

      expect(text).to include(
        "20 records are displayed per page"
      )

      expect(text).to include(
        "No additional pagination gem required"
      )

      expect(text).to include(
        "Works with b4um Bento and Table layouts"
      )

      expect(text).to include(
        "Invalid or excessive page numbers are handled safely"
      )
    end

    generator.show_help
  end

  it "documents the b4um infinite scroll generator" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "INFINITE SCROLL"
      )

      expect(text).to include(
        "bin/rails generate b4um:infinite_scroll MODEL"
      )

      expect(text).to include(
        "bin/rails generate b4um:infinite_scroll Product"
      )

      expect(text).to include(
        "bin/rails generate b4um:infinite_scroll Product --per-page=50"
      )

      expect(text).to include(
        "20 records are loaded per page"
      )

      expect(text).to include(
        "Works with b4um Bento and Table layouts"
      )

      expect(text).to include(
        "Replaces existing b4um pagination navigation"
      )

      expect(text).to include(
        "No additional pagination gem required"
      )
    end

    generator.show_help
  end

  it "documents the b4um search generator" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "SEARCH"
      )

      expect(text).to include(
        "bin/rails generate b4um:search MODEL"
      )

      expect(text).to include(
        "bin/rails generate b4um:search Product"
      )

      expect(text).to include(
        "Searches all string and text columns"
      )

      expect(text).to include(
        "Case-insensitive partial matching"
      )

      expect(text).to include(
        "Works with b4um Bento and Table layouts"
      )

      expect(text).to include(
        "Works with b4um Pagination and Infinite Scroll"
      )

      expect(text).to include(
        "No additional search gem required"
      )
    end

    generator.show_help
  end

  it "documents the b4um comments generator" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "COMMENTS"
      )

      expect(text).to include(
        "bin/rails generate b4um:comments MODEL"
      )

      expect(text).to include(
        "bin/rails generate b4um:comments Article"
      )

      expect(text).to include(
        "Polymorphic Comment model"
      )

      expect(text).to include(
        "Support for multiple commentable models"
      )

      expect(text).to include(
        "bin/rails generate b4um:comments Product"
      )

      expect(text).to include(
        "Unknown custom comments controllers are left unchanged"
      )
    end

    generator.show_help
  end

  it "documents the b4um Trix generator" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "TRIX / RICH TEXT"
      )

      expect(text).to include(
        "bin/rails generate b4um:trix MODEL ATTRIBUTE"
      )

      expect(text).to include(
        "bin/rails generate b4um:trix Article content"
      )

      expect(text).to include(
        "Action Text"
      )

      expect(text).to include(
        "has_rich_text :content"
      )

      expect(text).to include(
        "rich_text_area"
      )

      expect(text).to include(
        "Image lightbox"
      )

      expect(text).to include(
        "The model and form must already exist."
      )
    end

    generator.show_help
  end

  it "documents b4um authentication" do
    generator = described_class.new

    expect(generator).to receive(:say) do |text|
      expect(text).to include(
        "AUTHENTICATION"
      )

      expect(text).to include(
        "bin/rails generate b4um:authentication MODEL"
      )

      expect(text).to include(
        "bin/rails generate b4um:authentication User"
      )

      expect(text).to include(
        "has_secure_password"
      )

      expect(text).to include(
        "password_digest"
      )

      expect(text).to include(
        "bcrypt"
      )

      expect(text).to include(
        "Sessions controller"
      )

      expect(text).to include(
        "Login and logout routes"
      )

      expect(text).to include(
        "current_user"
      )

      expect(text).to include(
        "current_admin"
      )

      expect(text).to include(
        "Authentication uses an email attribute for login."
      )

      expect(text).to include(
        "Repeated generator runs do not duplicate"
      )

      expect(text).to include(
        "--protect=Products"
      )

      expect(text).to include(
        "--protect=Products,Articles,Comments"
      )

      expect(text).to include(
        "before_action :require_login, except: [:index, :show]"
      )

      expect(text).to include(
        "For protected b4um resources, authentication also updates"
      )

      expect(text).to include(
        "- New is hidden"
      )

      expect(text).to include(
        "- Edit is hidden"
      )

      expect(text).to include(
        "- Destroy is hidden"
      )

      expect(text).to include(
        "- Back remains visible"
      )

      expect(text).to include(
        "The controller protection remains the security boundary"
      )

      expect(text).to include(
        "Additional controllers can be protected later"
      )

      expect(text).to include(
        "All controllers passed to --protect must already exist."
      )

      expect(text).to include(
        "before changing the application"
      )
    end

    generator.show_help
  end
end
